### ISSUE TITLE
Possibly wrong key name

### ISSUE THREAD

**Issue by weidengeist** [kodolinija/stardeus-translations#111]
Hi @spajus,

after the `no.task` keys there is a `no.tasks` (plural) key appended with `rason` instead of `reason` (`no.tasks.rason.clock.stopped`). This is the case in the English base file and so certainly in all other language files derived from the English one. Maybe the key name is not that important anyway and the game logic is linked to the (potentially) misspelled key, but I think I should let you know.

Regards,
Weidengeist

**Comment by spajus** [comment]
Hey @weidengeist. Good catch, but I have the mistyped key in game too apparently 😄 I will keep the mistype in the sheet, to avoid having to change it in all the translations.
