### ISSUE TITLE
Please, add a specific key for these texts

### ISSUE THREAD

**Issue by xupisco** [kodolinija/stardeus-translations#386]
![image](https://github.com/user-attachments/assets/454f1881-0e9d-4f17-925a-dbb35a1927d1)

My OCD can't handle the word wrap in "Trabalhador".

**Comment by xupisco** [comment]
Not sure if is the right place, but is there any plans to let the user customize the UI colors? (The new one is tooooo saturated!). Tks

**Comment by spajus** [comment]
I will add new keys for being groups in next couple of days. 

As of UI colors, it is possible to create a mod that will override them, the colors are defined in Mods/Core/Config/Colors/UI - there are five subfolders there (Main, Saturated, White, Grey, Greyish) that define the palette variations.

**Comment by xupisco** [comment]
:)
![image](https://github.com/user-attachments/assets/872a3b55-f532-4d57-bb64-efb18fd15038)
