### ISSUE TITLE
Source string not found

### ISSUE THREAD

**Issue by xupisco** [kodolinija/stardeus-translations#392]
Can't find the key to the message below...
![image](https://github.com/user-attachments/assets/18a70784-6e5e-4bb0-ab6c-9e941a53493b)

**Comment by spajus** [comment]
Looks like this text is hardcoded, I've added `connector.ship.cpu.tip` into google sheets, the translation key will be used in the next build.

**Comment by xupisco** [comment]
Hi @spajus another one (I think)

![image](https://github.com/user-attachments/assets/4ad78bfd-d813-4f42-9b23-0c28b1824b6a)

In the "Rooms Overview"
:)

**Comment by xupisco** [comment]
> Hi @spajus another one (I think)
> 
> ![image](https://private-user-images.githubusercontent.com/10261/351386991-4ad78bfd-d813-4f42-9b23-0c28b1824b6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NDg0NTUsIm5iZiI6MTcyMTc0ODE1NSwicGF0aCI6Ii8xMDI2MS8zNTEzODY5OTEtNGFkNzhiZmQtZDgxMy00ZjQyLTliMjMtMGMyOGIxODI0YjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDE1MjIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NTIxMzJlYThmZWFjM2FhMzkyODFkZDMyYWVlZmYwNTdlMWNhYzRjOTFlNTU0ZmVkZjZlYmE2NTFkNzljNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tW3VYAqy7WM94tBfbOG3QxCiyjoeUKs3oB8B70VUYOg)
> 
> In the "Rooms Overview" :)

I found it, sorry.
Nevermind!
