### ISSUE TITLE
Request to add auto resize to button text of "twitch.same.as.channel".

### ISSUE THREAD

**Issue by s-yurama** [kodolinija/stardeus-translations#403]
## description

The text field of button is too short for ```twitch.same.as.channel```.
so, this was difficult to handle in side of translation.

## recommended solution or request

Please, add auto resize to this field.

**Comment by spajus** [comment]
This is likely due to Japanese font being taller than English, so it can't split into two lines. I'll see what I can do, auto-resize of the button itself is technically difficult, as a workaround I suggest to use one word translation: "same".

**Comment by s-yurama** [comment]
Sure. I'll replace it to like that, at the moment. 👌
